server:
  port: 8080

jwt:
  secret: 'PryalkinPavelPavlovich'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate:
      ddl-auto: true
